// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMHoPmAFIIayN1wcBCeC1t5JyWn6rgnWI',
    appId: '1:1034406495104:web:47f0b276ce0e82ff13b765',
    messagingSenderId: '1034406495104',
    projectId: 'todolist-c0d64',
    authDomain: 'todolist-c0d64.firebaseapp.com',
    storageBucket: 'todolist-c0d64.appspot.com',
    measurementId: 'G-YTSEENTMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnWwt1k4LOZfEb1c1YU_5A4V2UTBRNO48',
    appId: '1:1034406495104:android:bc19bc8ad5be047713b765',
    messagingSenderId: '1034406495104',
    projectId: 'todolist-c0d64',
    storageBucket: 'todolist-c0d64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkasCwWnprJEyVsBTKyHL_1P_feFXWQDs',
    appId: '1:1034406495104:ios:839517dbed0ab75b13b765',
    messagingSenderId: '1034406495104',
    projectId: 'todolist-c0d64',
    storageBucket: 'todolist-c0d64.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkasCwWnprJEyVsBTKyHL_1P_feFXWQDs',
    appId: '1:1034406495104:ios:839517dbed0ab75b13b765',
    messagingSenderId: '1034406495104',
    projectId: 'todolist-c0d64',
    storageBucket: 'todolist-c0d64.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMHoPmAFIIayN1wcBCeC1t5JyWn6rgnWI',
    appId: '1:1034406495104:web:23a636b3435d27f813b765',
    messagingSenderId: '1034406495104',
    projectId: 'todolist-c0d64',
    authDomain: 'todolist-c0d64.firebaseapp.com',
    storageBucket: 'todolist-c0d64.appspot.com',
    measurementId: 'G-WK0MRN7P4V',
  );
}
